import React, { useState } from 'react';
import { Megaphone, Sparkles, Copy, Check, Eye, Clock, X, BellRing, Palette, Layout } from 'lucide-react';
import { toast } from 'sonner';

interface BannerPreset {
  id: string;
  name: string;
  badge: string;
  text: string;
  ctaText: string;
  ctaUrl: string;
  bgGradient: string;
  textColor: string;
}

const PRESETS: BannerPreset[] = [
  {
    id: 'adelaide-sameday',
    name: 'Same-Day Adelaide Dispatch',
    badge: '🚀 SAME-DAY DISPATCH',
    text: 'Order before 2:00 PM ACST for same-day Adelaide courier dispatch!',
    ctaText: 'Shop In-Stock Gear',
    ctaUrl: '/shop/',
    bgGradient: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
    textColor: '#FFFFFF',
  },
  {
    id: 'holiday-notice',
    name: 'Public Holiday Warehouse Notice',
    badge: '📢 HOLIDAY NOTICE',
    text: 'Our Adelaide warehouse will be closed on Monday for the Public Holiday. Orders dispatch Tuesday.',
    ctaText: 'View Schedule',
    ctaUrl: '/shipping-info/',
    bgGradient: 'linear-gradient(135deg, #1E293B 0%, #0F172A 100%)',
    textColor: '#FFFFFF',
  },
  {
    id: 'free-freight-weekend',
    name: 'Free Shipping Weekend Promo',
    badge: '🚚 LIMITED TIME',
    text: 'FREE Express Delivery on all orders over $99 AUD this weekend only!',
    ctaText: 'Claim Free Shipping',
    ctaUrl: '/shop/',
    bgGradient: 'linear-gradient(135deg, #2563EB 0%, #1D4ED8 100%)',
    textColor: '#FFFFFF',
  },
  {
    id: 'clearance-flash',
    name: 'Flash Sale / Clearance Alert',
    badge: '🔥 CLEARANCE DEALS',
    text: 'Save up to 40% on enterprise networking switches, monitors & CCTV gear.',
    ctaText: 'Explore Deals',
    ctaUrl: '/sale/',
    bgGradient: 'linear-gradient(135deg, #DC2626 0%, #991B1B 100%)',
    textColor: '#FFFFFF',
  },
];

export const AnnouncementBannerStudio: React.FC = () => {
  const [selectedPreset, setSelectedPreset] = useState<BannerPreset>(PRESETS[0]);
  const [bannerText, setBannerText] = useState(PRESETS[0].text);
  const [badgeText, setBadgeText] = useState(PRESETS[0].badge);
  const [ctaText, setCtaText] = useState(PRESETS[0].ctaText);
  const [ctaUrl, setCtaUrl] = useState(PRESETS[0].ctaUrl);
  const [isDismissible, setIsDismissible] = useState(true);
  const [enableCountdown, setEnableCountdown] = useState(true);

  // Generate lightweight PHP snippet that hooks cleanly into wp_body_open
  const phpCode = `<?php
/**
 * Lightweight Store Announcement Banner
 * Generated by Vibe WP (Zero Bloat, Vanilla CSS & JS)
 */
add_action('wp_body_open', function() {
    ?>
    <div id="vibe-store-banner" style="background: ${selectedPreset.bgGradient}; color: ${selectedPreset.textColor}; padding: 10px 16px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 13px; font-weight: 500; display: flex; align-items: center; justify-content: center; position: relative; z-index: 99999; box-shadow: 0 2px 8px rgba(0,0,0,0.15);">
        <div style="display: flex; align-items: center; gap: 10px; flex-wrap: wrap; text-align: center; justify-content: center;">
            <span style="background: rgba(255,255,255,0.2); padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px;">${badgeText}</span>
            <span>${bannerText}</span>
            ${enableCountdown ? '<span id="vibe-banner-timer" style="background: rgba(0,0,0,0.25); padding: 2px 8px; border-radius: 4px; font-family: monospace; font-size: 12px; font-weight: 700;">⏱ 2h 45m left</span>' : ''}
            <a href="${ctaUrl}" style="background: #ffffff; color: #0f172a; padding: 4px 12px; border-radius: 6px; font-size: 12px; font-weight: 600; text-decoration: none; margin-left: 6px; transition: opacity 0.2s;" onmouseover="this.style.opacity=0.9" onmouseout="this.style.opacity=1">${ctaText} &rarr;</a>
        </div>
        ${isDismissible ? '<button onclick="document.getElementById(\\'vibe-store-banner\\').style.display=\\'none\\'; localStorage.setItem(\\'vibe_banner_closed\\', \\'true\\');" style="position: absolute; right: 12px; background: transparent; border: none; color: ' + selectedPreset.textColor + '; font-size: 16px; cursor: pointer; padding: 4px; opacity: 0.8;" title="Dismiss">&times;</button>' : ''}
    </div>
    <script>
    if (localStorage.getItem('vibe_banner_closed') === 'true') {
        var b = document.getElementById('vibe-store-banner');
        if (b) b.style.display = 'none';
    }
    </script>
    <?php
});`;

  const handleCopy = () => {
    navigator.clipboard.writeText(phpCode);
    toast.success(`Copied announcement banner code for ${selectedPreset.name}!`);
  };

  const handleSelectPreset = (p: BannerPreset) => {
    setSelectedPreset(p);
    setBannerText(p.text);
    setBadgeText(p.badge);
    setCtaText(p.ctaText);
    setCtaUrl(p.ctaUrl);
  };

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-amber-500 via-orange-600 to-red-600 flex items-center justify-center text-white shadow-md">
              <Megaphone className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-foreground">Store Announcement Banners & Notice Studio</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-500/10 text-amber-600 border border-amber-500/20 uppercase">
                  Daily Merchandising
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Deploy lightweight announcement bars (Same-Day Adelaide dispatch, Holiday notices, Free shipping weekends) with zero plugins.
              </p>
            </div>
          </div>

          <button
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1.5 shadow-sm whitespace-nowrap"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>Copy Banner PHP Snippet</span>
          </button>
        </div>

        {/* Preset Selector Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pt-2">
          {PRESETS.map((p) => (
            <button
              key={p.id}
              onClick={() => handleSelectPreset(p)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                selectedPreset.id === p.id
                  ? 'bg-amber-600 text-white shadow-sm'
                  : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
              }`}
            >
              {p.name}
            </button>
          ))}
        </div>
      </div>

      {/* Live Interactive Preview Banner */}
      <div className="rounded-2xl border border-border overflow-hidden shadow-sm space-y-2">
        <div className="px-4 py-2 bg-muted/40 border-b border-border flex items-center justify-between text-xs text-muted-foreground font-mono">
          <span>Live Customer View Preview</span>
          <span className="text-[10px] uppercase font-bold text-emerald-600">Active Header Preview</span>
        </div>
        <div
          style={{ background: selectedPreset.bgGradient, color: selectedPreset.textColor }}
          className="p-3.5 px-6 flex items-center justify-between gap-4 transition-all"
        >
          <div className="flex items-center gap-2.5 flex-wrap justify-center w-full text-xs font-medium">
            <span className="px-2 py-0.5 rounded bg-white/20 text-[10px] font-bold tracking-wider">{badgeText}</span>
            <span>{bannerText}</span>
            {enableCountdown && (
              <span className="px-2 py-0.5 rounded bg-black/25 font-mono text-[11px] font-bold flex items-center gap-1">
                <Clock className="w-3 h-3" />
                <span>2h 45m left</span>
              </span>
            )}
            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              className="px-3 py-1 rounded-md bg-white text-slate-900 font-bold text-[11px] shadow-sm hover:opacity-90 transition-opacity ml-1"
            >
              {ctaText} &rarr;
            </a>
          </div>
          {isDismissible && (
            <button className="text-white/80 hover:text-white p-1" title="Dismiss preview">
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Configuration & Code Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Banner Settings */}
        <div className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4">
          <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b border-border pb-3">
            <Palette className="w-4 h-4 text-amber-500" />
            <span>Customize Notice Details</span>
          </h3>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-foreground">Badge Label:</label>
            <input
              type="text"
              value={badgeText}
              onChange={(e) => setBadgeText(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-semibold text-foreground focus:outline-none"
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-foreground">Announcement Text:</label>
            <input
              type="text"
              value={bannerText}
              onChange={(e) => setBannerText(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs text-foreground focus:outline-none"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">CTA Button Text:</label>
              <input
                type="text"
                value={ctaText}
                onChange={(e) => setCtaText(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs text-foreground focus:outline-none"
              />
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">CTA Button Link:</label>
              <input
                type="text"
                value={ctaUrl}
                onChange={(e) => setCtaUrl(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-mono text-foreground focus:outline-none"
              />
            </div>
          </div>

          {/* Toggles */}
          <div className="space-y-2 pt-1">
            <label className="flex items-center justify-between p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer">
              <span className="text-xs font-semibold text-foreground">Show Countdown Timer</span>
              <input
                type="checkbox"
                checked={enableCountdown}
                onChange={(e) => setEnableCountdown(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary"
              />
            </label>

            <label className="flex items-center justify-between p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer">
              <span className="text-xs font-semibold text-foreground">Dismissible (Remembers via localStorage)</span>
              <input
                type="checkbox"
                checked={isDismissible}
                onChange={(e) => setIsDismissible(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary"
              />
            </label>
          </div>
        </div>

        {/* Right: Generated PHP Hook */}
        <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm flex flex-col">
          <div className="px-4 py-3 border-b border-border bg-muted/40 flex items-center justify-between">
            <span className="text-xs font-mono text-muted-foreground">Generated PHP Code (functions.php)</span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1 shadow-sm"
            >
              <Copy className="w-3 h-3" />
              <span>Copy</span>
            </button>
          </div>
          <div className="p-4 flex-1 bg-muted/20 font-mono text-xs text-foreground overflow-x-auto max-h-[380px]">
            <pre className="leading-relaxed text-amber-600 dark:text-amber-400">{phpCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
