import React, { useState } from 'react';
import { Layers, Plus, Copy, Check, Sparkles, FolderTree, Code2, Database } from 'lucide-react';
import { toast } from 'sonner';

interface CptPreset {
  id: string;
  name: string;
  singular: string;
  plural: string;
  slug: string;
  icon: string;
  supports: string[];
  taxonomy: string;
  taxSingular: string;
}

const PRESETS: CptPreset[] = [
  {
    id: 'case-studies',
    name: 'Case Studies',
    singular: 'Case Study',
    plural: 'Case Studies',
    slug: 'case-studies',
    icon: 'dashicons-portfolio',
    supports: ['title', 'editor', 'thumbnail', 'excerpt', 'custom-fields'],
    taxonomy: 'project-industry',
    taxSingular: 'Industry',
  },
  {
    id: 'team-members',
    name: 'Team Members',
    singular: 'Team Member',
    plural: 'Team Members',
    slug: 'team',
    icon: 'dashicons-groups',
    supports: ['title', 'editor', 'thumbnail', 'custom-fields'],
    taxonomy: 'department',
    taxSingular: 'Department',
  },
  {
    id: 'services',
    name: 'Services',
    singular: 'Service',
    plural: 'Services',
    slug: 'services',
    icon: 'dashicons-networking',
    supports: ['title', 'editor', 'thumbnail', 'excerpt'],
    taxonomy: 'service-category',
    taxSingular: 'Service Category',
  },
];

export const CptGeneratorStudio: React.FC = () => {
  const [selectedPreset, setSelectedPreset] = useState<CptPreset>(PRESETS[0]);
  const [enableRest, setEnableRest] = useState(true);
  const [hasArchive, setHasArchive] = useState(true);

  // Generate complete production PHP registration snippet
  const phpCode = `<?php
/**
 * Register Custom Post Type: ${selectedPreset.plural}
 * Generated by Vibe WP CPT & Taxonomy Studio
 */
add_action('init', function() {
    // 1. Register Taxonomy: ${selectedPreset.taxSingular}
    register_taxonomy('${selectedPreset.taxonomy}', ['${selectedPreset.slug}'], [
        'labels' => [
            'name' => '${selectedPreset.taxSingular}s',
            'singular_name' => '${selectedPreset.taxSingular}',
            'search_items' => 'Search ${selectedPreset.taxSingular}s',
            'all_items' => 'All ${selectedPreset.taxSingular}s',
            'edit_item' => 'Edit ${selectedPreset.taxSingular}',
            'update_item' => 'Update ${selectedPreset.taxSingular}',
            'add_new_item' => 'Add New ${selectedPreset.taxSingular}',
            'menu_name' => '${selectedPreset.taxSingular}s',
        ],
        'hierarchical' => true,
        'show_ui' => true,
        'show_admin_column' => true,
        'show_in_rest' => ${enableRest ? 'true' : 'false'},
        'query_var' => true,
        'rewrite' => ['slug' => '${selectedPreset.taxonomy}'],
    ]);

    // 2. Register Post Type: ${selectedPreset.singular}
    register_post_type('${selectedPreset.slug}', [
        'labels' => [
            'name' => '${selectedPreset.plural}',
            'singular_name' => '${selectedPreset.singular}',
            'add_new' => 'Add New ${selectedPreset.singular}',
            'add_new_item' => 'Add New ${selectedPreset.singular}',
            'edit_item' => 'Edit ${selectedPreset.singular}',
            'new_item' => 'New ${selectedPreset.singular}',
            'view_item' => 'View ${selectedPreset.singular}',
            'search_items' => 'Search ${selectedPreset.plural}',
            'not_found' => 'No ${selectedPreset.plural} found',
            'menu_name' => '${selectedPreset.plural}',
        ],
        'public' => true,
        'has_archive' => ${hasArchive ? 'true' : 'false'},
        'show_in_rest' => ${enableRest ? 'true' : 'false'},
        'menu_icon' => '${selectedPreset.icon}',
        'supports' => ${JSON.stringify(selectedPreset.supports).replace(/"/g, "'")},
        'taxonomies' => ['${selectedPreset.taxonomy}'],
        'rewrite' => ['slug' => '${selectedPreset.slug}'],
    ]);
});`;

  const handleCopy = () => {
    navigator.clipboard.writeText(phpCode);
    toast.success(`Copied CPT registration for ${selectedPreset.name}!`);
  };

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-700 flex items-center justify-center text-white shadow-md">
              <FolderTree className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-foreground">Custom Post Type & Taxonomy Scaffolder Studio</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-blue-500/10 text-blue-600 border border-blue-500/20 uppercase">
                  REST API & Gutenberg Ready
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Generate production-ready CPTs with hierarchical taxonomies, REST API endpoints, Dashicons, and archive rules.
              </p>
            </div>
          </div>

          <button
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1.5 shadow-sm whitespace-nowrap"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>Copy CPT Registration Code</span>
          </button>
        </div>

        {/* Preset Selector Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pt-2">
          {PRESETS.map((preset) => (
            <button
              key={preset.id}
              onClick={() => setSelectedPreset(preset)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                selectedPreset.id === preset.id
                  ? 'bg-primary text-primary-foreground shadow-sm'
                  : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
              }`}
            >
              {preset.name}
            </button>
          ))}
        </div>
      </div>

      {/* Editor & Configuration Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: CPT Settings */}
        <div className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4">
          <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b border-border pb-3">
            <Database className="w-4 h-4 text-primary" />
            <span>CPT Architecture: {selectedPreset.name}</span>
          </h3>

          <div className="grid grid-cols-2 gap-3 text-xs">
            <div className="p-3 rounded-xl bg-muted/40 border border-border space-y-1">
              <span className="text-muted-foreground font-mono">Post Type Slug:</span>
              <div className="font-mono font-bold text-foreground"><code>{selectedPreset.slug}</code></div>
            </div>
            <div className="p-3 rounded-xl bg-muted/40 border border-border space-y-1">
              <span className="text-muted-foreground font-mono">Taxonomy Slug:</span>
              <div className="font-mono font-bold text-foreground"><code>{selectedPreset.taxonomy}</code></div>
            </div>
          </div>

          {/* Toggles */}
          <div className="space-y-3 pt-2">
            <label className="flex items-center justify-between p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Enable WordPress REST API (show_in_rest)</div>
                <p className="text-[11px] text-muted-foreground">Required for Block Editor (Gutenberg) & Headless Next.js.</p>
              </div>
              <input
                type="checkbox"
                checked={enableRest}
                onChange={(e) => setEnableRest(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary"
              />
            </label>

            <label className="flex items-center justify-between p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Enable Archive Page (has_archive)</div>
                <p className="text-[11px] text-muted-foreground">Enables <code>/{selectedPreset.slug}/</code> archive listings.</p>
              </div>
              <input
                type="checkbox"
                checked={hasArchive}
                onChange={(e) => setHasArchive(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary"
              />
            </label>
          </div>
        </div>

        {/* Right: Code Output */}
        <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm flex flex-col">
          <div className="px-4 py-3 border-b border-border bg-muted/40 flex items-center justify-between">
            <span className="text-xs font-mono text-muted-foreground">Generated PHP Snippet (functions.php)</span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1 shadow-sm"
            >
              <Copy className="w-3 h-3" />
              <span>Copy</span>
            </button>
          </div>
          <div className="p-4 flex-1 bg-muted/20 font-mono text-xs text-foreground overflow-x-auto max-h-[380px]">
            <pre className="leading-relaxed text-blue-600 dark:text-blue-400">{phpCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
