import React, { useState } from 'react';
import { Image as ImageIcon, Search, Download, Check, Sparkles, Copy, ExternalLink, ShieldCheck, RefreshCw, Layers } from 'lucide-react';
import { toast } from 'sonner';

interface ProductImagePreset {
  id: string;
  brand: string;
  mpn: string;
  title: string;
  category: string;
  sampleImageUrl: string;
}

const PRESETS: ProductImagePreset[] = [
  {
    id: 'ubiquiti-switch',
    brand: 'Ubiquiti',
    mpn: 'USW-24-POE',
    title: 'Ubiquiti UniFi 24-Port Gigabit PoE+ Managed Switch (95W)',
    category: 'Networking',
    sampleImageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'dell-laptop',
    brand: 'Dell',
    mpn: 'LAT-5540-I7',
    title: 'Dell Latitude 5540 15.6" FHD Laptop Intel Core i7 16GB 512GB SSD',
    category: 'Laptops',
    sampleImageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'hikvision-cctv',
    brand: 'Hikvision',
    mpn: 'DS-2CD2387G2-LU',
    title: 'Hikvision ColorVu 8MP 4K IP Turret Camera 2.8mm Fixed Lens',
    category: 'CCTV & Security',
    sampleImageUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'hp-laserjet',
    brand: 'HP',
    mpn: '3102FDW',
    title: 'HP LaserJet Pro MFP 3102fdw Wireless Monochrome Laser Printer',
    category: 'Printers',
    sampleImageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
  },
];

export const ImageResolverStudio: React.FC = () => {
  const [selectedPreset, setSelectedPreset] = useState<ProductImagePreset>(PRESETS[0]);
  const [productId, setProductId] = useState('4821');
  const [brand, setBrand] = useState(PRESETS[0].brand);
  const [mpn, setMpn] = useState(PRESETS[0].mpn);
  const [productTitle, setProductTitle] = useState(PRESETS[0].title);
  const [resolvedImageUrl, setResolvedImageUrl] = useState(PRESETS[0].sampleImageUrl);
  const [isResolving, setIsResolving] = useState(false);

  const handleSelectPreset = (p: ProductImagePreset) => {
    setSelectedPreset(p);
    setBrand(p.brand);
    setMpn(p.mpn);
    setProductTitle(p.title);
    setResolvedImageUrl(p.sampleImageUrl);
  };

  const handleSimulateFetch = () => {
    setIsResolving(true);
    setTimeout(() => {
      setIsResolving(false);
      toast.success(`Successfully resolved high-res photo for ${brand} ${mpn}!`);
    }, 600);
  };

  // Generate PHP snippet for Antigravity or direct execution in WordPress
  const phpCode = `<?php
/**
 * Attach High-Res Image to WooCommerce Product #${productId}
 * Generated by Vibe WP Image Resolver (Zero Bloat)
 */
require_once(ABSPATH . 'wp-admin/includes/media.php');
require_once(ABSPATH . 'wp-admin/includes/file.php');
require_once(ABSPATH . 'wp-admin/includes/image.php');

$product_id = ${productId};
$image_url = '${resolvedImageUrl}';
$description = '${brand} ${mpn} - ${productTitle}';

// 1. Download & Sideload Image into /wp-content/uploads/
$attachment_id = media_sideload_image($image_url, $product_id, $description, 'id');

if (!is_wp_error($attachment_id)) {
    // 2. Set as Featured Thumbnail
    set_post_thumbnail($product_id, $attachment_id);
    
    // 3. Set Alt Text for Google Image SEO
    update_post_meta($attachment_id, '_wp_attachment_image_alt', $description);
    
    echo "✔ Successfully downloaded and attached featured image (ID: $attachment_id) to Product #${productId}!";
} else {
    echo "❌ Error sideloading image: " . $attachment_id->get_error_message();
}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(phpCode);
    toast.success(`Copied image sideload PHP snippet for Product #${productId}!`);
  };

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-purple-600 via-pink-600 to-rose-600 flex items-center justify-center text-white shadow-md">
              <ImageIcon className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-foreground">AI Product Image Resolver & Sideload Studio</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-purple-500/10 text-purple-600 border border-purple-500/20 uppercase">
                  Antigravity Live Tester
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Look up missing feed product images by Brand and MPN, preview high-res photos, and attach directly to WooCommerce products.
              </p>
            </div>
          </div>

          <button
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1.5 shadow-sm whitespace-nowrap"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>Copy Sideload Snippet</span>
          </button>
        </div>

        {/* Preset Selector Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pt-2">
          {PRESETS.map((p) => (
            <button
              key={p.id}
              onClick={() => handleSelectPreset(p)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                selectedPreset.id === p.id
                  ? 'bg-purple-600 text-white shadow-sm'
                  : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
              }`}
            >
              {p.brand} ({p.mpn})
            </button>
          ))}
        </div>
      </div>

      {/* Interactive Resolver & Live Preview Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Search & Sideload Controls */}
        <div className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4">
          <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b border-border pb-3">
            <Search className="w-4 h-4 text-purple-600" />
            <span>Product Image Lookup Parameters</span>
          </h3>

          <div className="grid grid-cols-3 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">Woo Product ID:</label>
              <input
                type="text"
                value={productId}
                onChange={(e) => setProductId(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-mono text-foreground focus:outline-none"
              />
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">Brand Name:</label>
              <input
                type="text"
                value={brand}
                onChange={(e) => setBrand(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-semibold text-foreground focus:outline-none"
              />
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">Part Number (MPN):</label>
              <input
                type="text"
                value={mpn}
                onChange={(e) => setMpn(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-mono text-foreground focus:outline-none"
              />
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-foreground">Product Title:</label>
            <input
              type="text"
              value={productTitle}
              onChange={(e) => setProductTitle(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs text-foreground focus:outline-none"
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-foreground">Resolved Image URL (Source):</label>
            <input
              type="text"
              value={resolvedImageUrl}
              onChange={(e) => setResolvedImageUrl(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-mono text-muted-foreground focus:outline-none"
            />
          </div>

          <div className="flex items-center gap-3 pt-2">
            <button
              onClick={handleSimulateFetch}
              disabled={isResolving}
              className="flex-1 py-2.5 px-4 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-semibold flex items-center justify-center gap-2 shadow-sm transition-all"
            >
              {isResolving ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
              <span>{isResolving ? 'Searching Global Catalog...' : 'Look Up High-Res Image'}</span>
            </button>
          </div>

          {/* Live Image Card Preview */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 space-y-3">
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-foreground">Live Resolved Image Preview:</span>
              <span className="font-mono text-[11px] text-purple-600 font-bold">1200 x 800 (WebP / JPEG)</span>
            </div>
            <div className="w-full h-48 rounded-lg overflow-hidden border border-border bg-background flex items-center justify-center relative group">
              <img
                src={resolvedImageUrl}
                alt={`${brand} ${mpn}`}
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
              />
              <div className="absolute top-2 left-2 px-2 py-1 rounded bg-black/70 text-white font-mono text-[10px] font-bold">
                {brand} • {mpn}
              </div>
            </div>
          </div>
        </div>

        {/* Right: Generated PHP Execution Snippet */}
        <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm flex flex-col">
          <div className="px-4 py-3 border-b border-border bg-muted/40 flex items-center justify-between">
            <span className="text-xs font-mono text-muted-foreground">Generated WordPress Media Sideload Code</span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1 shadow-sm"
            >
              <Copy className="w-3 h-3" />
              <span>Copy</span>
            </button>
          </div>
          <div className="p-4 flex-1 bg-muted/20 font-mono text-xs text-foreground overflow-x-auto max-h-[480px]">
            <pre className="leading-relaxed text-purple-700 dark:text-purple-300">{phpCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
