import React, { useState } from 'react';
import { Package, Truck, Copy, Check, Sparkles, Send, CheckCircle2, Search, Clock, ExternalLink } from 'lucide-react';
import { toast } from 'sonner';

interface Courier {
  id: string;
  name: string;
  urlTemplate: string;
  exampleTracking: string;
}

const COURIERS: Courier[] = [
  {
    id: 'auspost',
    name: 'Australia Post',
    urlTemplate: 'https://auspost.com.au/mypost/track/#/details/{TRACKING}',
    exampleTracking: 'AP982348123AU',
  },
  {
    id: 'startrack',
    name: 'StarTrack Express',
    urlTemplate: 'https://startrack.com.au/track/details/{TRACKING}',
    exampleTracking: 'ST78923412',
  },
  {
    id: 'tnt',
    name: 'TNT / FedEx Australia',
    urlTemplate: 'https://www.tnt.com/express/en_au/site/shipping-tools/tracking.html?searchType=CON&cons={TRACKING}',
    exampleTracking: 'TNT9081234',
  },
  {
    id: 'couriersplease',
    name: 'CouriersPlease',
    urlTemplate: 'https://www.couriersplease.com.au/tools-track/no/{TRACKING}',
    exampleTracking: 'CP12345678',
  },
  {
    id: 'aramex',
    name: 'Aramex Australia (Fastway)',
    urlTemplate: 'https://www.aramex.com.au/tools/track?l={TRACKING}',
    exampleTracking: 'AR89234712',
  },
];

export const OrderTrackingStudio: React.FC = () => {
  const [orderId, setOrderId] = useState('4821');
  const [selectedCourier, setSelectedCourier] = useState<Courier>(COURIERS[0]);
  const [trackingNumber, setTrackingNumber] = useState(COURIERS[0].exampleTracking);
  const [newStatus, setNewStatus] = useState<'completed' | 'processing' | 'on-hold'>('completed');
  const [customerEmailNote, setCustomerEmailNote] = useState('Your order has been packed and dispatched from our Adelaide warehouse.');

  const trackingUrl = selectedCourier.urlTemplate.replace('{TRACKING}', trackingNumber);

  // Generate lightweight PHP snippet to execute or hook into WooCommerce
  const phpCode = `<?php
/**
 * Fast Order Management & Courier Tracking Dispatcher
 * Generated by Vibe WP for Order #${orderId}
 */
$order = wc_get_order(${orderId});

if ($order) {
    // 1. Save Courier Tracking Metadata
    $order->update_meta_data('_vibe_courier_name', '${selectedCourier.name}');
    $order->update_meta_data('_vibe_tracking_number', '${trackingNumber}');
    $order->update_meta_data('_vibe_tracking_url', '${trackingUrl}');

    // 2. Add Customer Note (Triggers Email to Customer)
    $tracking_note = "🚚 Courier Dispatch Update:\\n" .
                     "Courier: ${selectedCourier.name}\\n" .
                     "Tracking Number: ${trackingNumber}\\n" .
                     "Track Package: ${trackingUrl}\\n\\n" .
                     "${customerEmailNote}";
    $order->add_order_note($tracking_note, true); // true = sent to customer

    // 3. Update Order Status
    $order->update_status('${newStatus}', 'Order dispatched via ${selectedCourier.name} (${trackingNumber}).');
    $order->save();

    echo "✔ Order #${orderId} successfully updated to ${newStatus.toUpperCase()} with ${selectedCourier.name} tracking!";
} else {
    echo "❌ Order #${orderId} not found.";
}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(phpCode);
    toast.success(`Copied courier dispatch code for Order #${orderId}!`);
  };

  const handleSelectCourier = (courier: Courier) => {
    setSelectedCourier(courier);
    setTrackingNumber(courier.exampleTracking);
  };

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-700 flex items-center justify-center text-white shadow-md">
              <Truck className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-foreground">Order Management & Australian Courier Tracking Studio</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20 uppercase">
                  Daily Operations
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Dispatch orders, generate clickable Australia Post / StarTrack / TNT tracking URLs, and trigger customer completion emails with zero clicks.
              </p>
            </div>
          </div>

          <button
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1.5 shadow-sm whitespace-nowrap"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>Copy Dispatch Snippet</span>
          </button>
        </div>

        {/* Courier Selector Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pt-2">
          {COURIERS.map((c) => (
            <button
              key={c.id}
              onClick={() => handleSelectCourier(c)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                selectedCourier.id === c.id
                  ? 'bg-emerald-600 text-white shadow-sm'
                  : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
              }`}
            >
              {c.name}
            </button>
          ))}
        </div>
      </div>

      {/* Dispatch Controls & Live Preview Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Dispatch Order Form */}
        <div className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4">
          <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b border-border pb-3">
            <Package className="w-4 h-4 text-emerald-600" />
            <span>Dispatch Order Details</span>
          </h3>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">WooCommerce Order ID:</label>
              <div className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-muted/40 border border-border">
                <span className="text-xs text-muted-foreground font-mono">#</span>
                <input
                  type="text"
                  value={orderId}
                  onChange={(e) => setOrderId(e.target.value)}
                  className="w-full bg-transparent text-xs font-mono font-bold text-foreground focus:outline-none"
                  placeholder="e.g. 4821"
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-semibold text-foreground">Update Status To:</label>
              <select
                value={newStatus}
                onChange={(e) => setNewStatus(e.target.value as any)}
                className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-semibold text-foreground focus:outline-none"
              >
                <option value="completed">Completed (Dispatched)</option>
                <option value="processing">Processing</option>
                <option value="on-hold">On Hold</option>
              </select>
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-foreground">Courier Tracking Number:</label>
            <input
              type="text"
              value={trackingNumber}
              onChange={(e) => setTrackingNumber(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs font-mono text-foreground focus:outline-none"
              placeholder="e.g. AP982348123AU"
            />
          </div>

          {/* Clickable Tracking Preview */}
          <div className="p-3.5 rounded-xl bg-emerald-500/5 border border-emerald-500/20 space-y-1.5">
            <div className="text-[11px] font-mono font-bold text-emerald-600 flex items-center justify-between">
              <span>Live Generated Tracking URL:</span>
              <a
                href={trackingUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:underline flex items-center gap-1"
              >
                <span>Test Link</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
            <div className="text-xs font-mono text-muted-foreground truncate select-all">{trackingUrl}</div>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-foreground">Customer Email Dispatch Note:</label>
            <textarea
              rows={2}
              value={customerEmailNote}
              onChange={(e) => setCustomerEmailNote(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-muted/40 border border-border text-xs text-foreground focus:outline-none"
            />
          </div>
        </div>

        {/* Right: Generated PHP Execution Snippet */}
        <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm flex flex-col">
          <div className="px-4 py-3 border-b border-border bg-muted/40 flex items-center justify-between">
            <span className="text-xs font-mono text-muted-foreground">Generated WooCommerce Execution Snippet</span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1 shadow-sm"
            >
              <Copy className="w-3 h-3" />
              <span>Copy Snippet</span>
            </button>
          </div>
          <div className="p-4 flex-1 bg-muted/20 font-mono text-xs text-foreground overflow-x-auto max-h-[380px]">
            <pre className="leading-relaxed text-emerald-700 dark:text-emerald-300">{phpCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
