import React, { useState } from 'react';
import { ShieldAlert, ShieldCheck, Lock, Copy, Check, Sparkles, Terminal, FileCode, AlertTriangle, EyeOff } from 'lucide-react';
import { toast } from 'sonner';

export const SecurityHardeningStudio: React.FC = () => {
  const [blockXmlRpc, setBlockXmlRpc] = useState(true);
  const [blockUserEnum, setBlockUserEnum] = useState(true);
  const [blockUploadsPhp, setBlockUploadsPhp] = useState(true);
  const [hideWpVersion, setHideWpVersion] = useState(true);
  const [injectSecurityHeaders, setInjectSecurityHeaders] = useState(true);
  const [disableFileEdit, setDisableFileEdit] = useState(true);

  // Generate lightweight security snippet for functions.php / .htaccess
  const getSecurityCode = () => {
    let php = `<?php\n/**\n * WordPress Security Hardening & Bot Shield\n * Generated by Vibe WP\n */\n\n`;

    if (hideWpVersion) {
      php += `// 1. Hide WordPress Version Generator\nremove_action('wp_head', 'wp_generator');\nadd_filter('the_generator', '__return_empty_string');\n\n`;
    }

    if (blockUserEnum) {
      php += `// 2. Block REST API User Enumeration (Protects Admin Usernames)\nadd_filter('rest_endpoints', function($endpoints) {\n    if (!is_user_logged_in() && isset($endpoints['/wp/v2/users'])) {\n        unset($endpoints['/wp/v2/users']);\n    }\n    return $endpoints;\n});\n\n`;
    }

    if (blockXmlRpc) {
      php += `// 3. Disable XML-RPC (Prevents Brute Force & DDoS Pingbacks)\nadd_filter('xmlrpc_enabled', '__return_false');\nadd_filter('xmlrpc_methods', '__return_empty_array');\n\n`;
    }

    if (disableFileEdit) {
      php += `// 4. Disable In-Dashboard Theme/Plugin File Editor (In wp-config.php)\n// define('DISALLOW_FILE_EDIT', true);\n\n`;
    }

    if (injectSecurityHeaders) {
      php += `// 5. Inject Enterprise HTTP Security Headers\nadd_action('send_headers', function() {\n    header('X-Frame-Options: SAMEORIGIN');\n    header('X-Content-Type-Options: nosniff');\n    header('X-XSS-Protection: 1; mode=block');\n    header('Referrer-Policy: strict-origin-when-cross-origin');\n    header('Permissions-Policy: geolocation=(), camera=(), microphone=()');\n});\n`;
    }

    return php;
  };

  const getHtaccessCode = () => {
    let ht = `# Vibe WP Security Rules (.htaccess)\n\n`;

    if (blockUploadsPhp) {
      ht += `# Block PHP Execution in Uploads Folder\n<Directory "/wp-content/uploads">\n    <Files "*.php">\n        Order Deny,Allow\n        Deny from all\n    </Files>\n</Directory>\n\n`;
    }

    if (blockXmlRpc) {
      ht += `# Block xmlrpc.php Requests\n<Files xmlrpc.php>\n    Order Deny,Allow\n    Deny from all\n</Files>\n\n`;
    }

    ht += `# Protect Sensitive Configuration Files\n<FilesMatch "^(wp-config\\.php|\\.env|\\.git|composer\\.json|debug\\.log)">\n    Order allow,deny\n    Deny from all\n</FilesMatch>\n`;

    return ht;
  };

  const [activeFormat, setActiveFormat] = useState<'php' | 'htaccess'>('php');

  const handleCopy = () => {
    const code = activeFormat === 'php' ? getSecurityCode() : getHtaccessCode();
    navigator.clipboard.writeText(code);
    toast.success(`Copied security hardening rules (${activeFormat.toUpperCase()})!`);
  };

  const securityScore = [blockXmlRpc, blockUserEnum, blockUploadsPhp, hideWpVersion, injectSecurityHeaders, disableFileEdit].filter(Boolean).length;
  const scorePercent = Math.round((securityScore / 6) * 100);

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-teal-600 to-emerald-700 flex items-center justify-center text-white shadow-md">
              <Lock className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-foreground">WordPress Security Hardening & Bot Shield Studio</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20 uppercase">
                  Zero Bloat Hardening
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Eliminates XML-RPC brute force attacks, blocks REST API user harvesting, protects wp-config/.env, and injects enterprise security headers.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <div className="px-3.5 py-2 rounded-xl bg-muted/60 border border-border text-center">
              <div className="text-[10px] font-mono text-muted-foreground font-bold uppercase">Shield Strength</div>
              <div className="text-sm font-bold text-emerald-600 font-mono">{scorePercent}% Protected</div>
            </div>
            <button
              onClick={handleCopy}
              className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1.5 shadow-sm whitespace-nowrap"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Security Rules</span>
            </button>
          </div>
        </div>

        {/* Format Switcher */}
        <div className="flex items-center gap-2 pt-2">
          <button
            onClick={() => setActiveFormat('php')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              activeFormat === 'php'
                ? 'bg-primary text-primary-foreground shadow-sm'
                : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
            }`}
          >
            PHP Rules (functions.php)
          </button>
          <button
            onClick={() => setActiveFormat('htaccess')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              activeFormat === 'htaccess'
                ? 'bg-primary text-primary-foreground shadow-sm'
                : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
            }`}
          >
            Server Rules (.htaccess)
          </button>
        </div>
      </div>

      {/* Toggles & Code Output Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Security Toggles */}
        <div className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4">
          <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b border-border pb-3">
            <ShieldCheck className="w-4 h-4 text-emerald-500" />
            <span>Hardening Rule Toggles</span>
          </h3>

          <div className="space-y-3">
            <label className="flex items-start justify-between gap-3 p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer transition-colors">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Block REST API User Enumeration</div>
                <p className="text-[11px] text-muted-foreground">Blocks <code>/wp-json/wp/v2/users</code> so bots cannot harvest admin logins.</p>
              </div>
              <input
                type="checkbox"
                checked={blockUserEnum}
                onChange={(e) => setBlockUserEnum(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary mt-1"
              />
            </label>

            <label className="flex items-start justify-between gap-3 p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer transition-colors">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Disable XML-RPC Pingbacks & Auth</div>
                <p className="text-[11px] text-muted-foreground">Eliminates brute force password attacks targeting <code>xmlrpc.php</code>.</p>
              </div>
              <input
                type="checkbox"
                checked={blockXmlRpc}
                onChange={(e) => setBlockXmlRpc(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary mt-1"
              />
            </label>

            <label className="flex items-start justify-between gap-3 p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer transition-colors">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Inject Enterprise HTTP Security Headers</div>
                <p className="text-[11px] text-muted-foreground">Adds <code>X-Frame-Options</code>, <code>X-XSS-Protection</code>, and strict origin headers.</p>
              </div>
              <input
                type="checkbox"
                checked={injectSecurityHeaders}
                onChange={(e) => setInjectSecurityHeaders(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary mt-1"
              />
            </label>

            <label className="flex items-start justify-between gap-3 p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer transition-colors">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Block PHP Execution in Uploads Directory</div>
                <p className="text-[11px] text-muted-foreground">Prevents backdoor PHP scripts uploaded via vulnerable form plugins from executing.</p>
              </div>
              <input
                type="checkbox"
                checked={blockUploadsPhp}
                onChange={(e) => setBlockUploadsPhp(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary mt-1"
              />
            </label>

            <label className="flex items-start justify-between gap-3 p-3 rounded-xl border border-border hover:bg-muted/20 cursor-pointer transition-colors">
              <div className="space-y-0.5">
                <div className="text-xs font-bold text-foreground">Hide WordPress Version Generator Meta</div>
                <p className="text-[11px] text-muted-foreground">Removes <code>&lt;meta name="generator" content="WordPress"&gt;</code> to prevent version probing.</p>
              </div>
              <input
                type="checkbox"
                checked={hideWpVersion}
                onChange={(e) => setHideWpVersion(e.target.checked)}
                className="w-4 h-4 rounded text-primary focus:ring-primary mt-1"
              />
            </label>
          </div>
        </div>

        {/* Right: Code Output */}
        <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm flex flex-col">
          <div className="px-4 py-3 border-b border-border bg-muted/40 flex items-center justify-between">
            <span className="text-xs font-mono text-muted-foreground">Generated Rules ({activeFormat === 'php' ? 'functions.php' : '.htaccess'})</span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1 shadow-sm"
            >
              <Copy className="w-3 h-3" />
              <span>Copy</span>
            </button>
          </div>
          <div className="p-4 flex-1 bg-muted/20 font-mono text-xs text-foreground overflow-x-auto max-h-[420px]">
            <pre className="leading-relaxed text-teal-600 dark:text-teal-400">
              {activeFormat === 'php' ? getSecurityCode() : getHtaccessCode()}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};
