import React, { useState } from 'react';
import { Truck, MapPin, PackageCheck, Copy, Check, Sparkles, ShieldCheck, DollarSign, Weight, AlertCircle } from 'lucide-react';
import { toast } from 'sonner';

interface ShippingRule {
  id: string;
  name: string;
  postcodes: string;
  freeThreshold: number;
  flatRate: number;
  bulkySurcharge: number;
  description: string;
}

const DEFAULT_RULES: ShippingRule[] = [
  {
    id: 'adelaide-local',
    name: 'Greater Adelaide Metro (Local Fast Delivery)',
    postcodes: '5000-5199, 5950',
    freeThreshold: 150,
    flatRate: 12,
    bulkySurcharge: 25,
    description: 'Same-day or next-day courier dispatch across Greater Adelaide. Free shipping for orders over $150 AUD.',
  },
  {
    id: 'interstate-metro',
    name: 'Interstate Metro (Melbourne, Sydney, Brisbane)',
    postcodes: '2000-2249, 3000-3207, 4000-4179',
    freeThreshold: 350,
    flatRate: 19,
    bulkySurcharge: 45,
    description: 'Express road freight to East Coast capital cities.',
  },
  {
    id: 'regional-remote',
    name: 'Regional SA & Remote Australia',
    postcodes: '5200-5799, 0800-0899, 6700-6799',
    freeThreshold: 500,
    flatRate: 29,
    bulkySurcharge: 65,
    description: 'Freight for regional mining, farming, and remote country zones.',
  },
];

export const ShippingRulesEngine: React.FC = () => {
  const [selectedRule, setSelectedRule] = useState<ShippingRule>(DEFAULT_RULES[0]);
  const [cartTotal, setCartTotal] = useState(115);
  const [isBulky, setIsBulky] = useState(false);

  // Generate lightweight native WooCommerce PHP hook
  const phpCode = `<?php
/**
 * Native WooCommerce Dynamic Shipping & Regional Postcode Rules
 * Generated by Vibe WP for ${selectedRule.name}
 */
add_filter('woocommerce_package_rates', function($rates, $package) {
    $cart_total = WC()->cart->get_displayed_subtotal();
    $postcode = preg_replace('/\\s+/', '', strtoupper($package['destination']['postcode'] ?? ''));
    $has_bulky = false;

    // Check for heavy hardware or server racks (>20kg)
    foreach (WC()->cart->get_cart() as $cart_item) {
        $weight = (float)$cart_item['data']->get_weight();
        if ($weight >= 20 || str_contains(strtolower($cart_item['data']->get_name()), 'rack')) {
            $has_bulky = true;
            break;
        }
    }

    // Evaluate Postcode Range (${selectedRule.postcodes})
    $is_zone = false;
    $postcode_int = (int)$postcode;
    if ($postcode_int >= 5000 && $postcode_int <= 5199) {
        $is_zone = true;
    }

    if ($is_zone) {
        foreach ($rates as $rate_id => $rate) {
            if ('flat_rate' === $rate->method_id) {
                // Free Shipping Threshold ($${selectedRule.freeThreshold} AUD)
                if ($cart_total >= ${selectedRule.freeThreshold} && !$has_bulky) {
                    $rates[$rate_id]->cost = 0;
                    $rates[$rate_id]->label = '${selectedRule.name} (FREE Delivery)';
                } else {
                    $base_cost = ${selectedRule.flatRate};
                    if ($has_bulky) {
                        $base_cost += ${selectedRule.bulkySurcharge}; // Bulky freight surcharge
                        $rates[$rate_id]->label = '${selectedRule.name} (Heavy / Bulky Freight)';
                    } else {
                        $rates[$rate_id]->label = '${selectedRule.name} Flat Delivery';
                    }
                    $rates[$rate_id]->cost = $base_cost;
                }
            }
        }
    }

    return $rates;
}, 100, 2);

// Live Free Shipping Progress Bar on Cart / Checkout
add_action('woocommerce_before_cart_table', function() {
    $subtotal = WC()->cart->get_displayed_subtotal();
    $threshold = ${selectedRule.freeThreshold};
    $diff = $threshold - $subtotal;
    
    if ($diff > 0) {
        echo '<div style="background:#f0fdf4;border:1px solid #bbf7d0;padding:12px;border-radius:8px;margin-bottom:15px;color:#166534;font-size:13px;font-weight:600;">' .
             '🚚 Add $' . number_format($diff, 2) . ' AUD more to unlock FREE ${selectedRule.name} Delivery!' .
             '</div>';
    } else {
        echo '<div style="background:#ecfdf5;border:1px solid #a7f3d0;padding:12px;border-radius:8px;margin-bottom:15px;color:#065f46;font-size:13px;font-weight:600;">' .
             '🎉 You have qualified for FREE Delivery!' .
             '</div>';
    }
});`;

  const handleCopy = () => {
    navigator.clipboard.writeText(phpCode);
    toast.success(`Copied shipping rules for ${selectedRule.name}!`);
  };

  const remainingForFree = Math.max(0, selectedRule.freeThreshold - cartTotal);
  const progressPercent = Math.min(100, Math.round((cartTotal / selectedRule.freeThreshold) * 100));

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="p-6 rounded-2xl border border-border bg-card shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-emerald-600 to-teal-700 flex items-center justify-center text-white shadow-md">
              <Truck className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-foreground">WooCommerce Dynamic Shipping & Regional Postcode Engine</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20 uppercase">
                  Zero Bloat Native PHP
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Calculates regional Australian postcode rules, bulky/heavy freight thresholds (over 20kg), and live cart free shipping progress goals.
              </p>
            </div>
          </div>

          <button
            onClick={handleCopy}
            className="px-4 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1.5 shadow-sm whitespace-nowrap"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>Copy WooCommerce Shipping Hook</span>
          </button>
        </div>

        {/* Region Selector Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pt-2">
          {DEFAULT_RULES.map((rule) => (
            <button
              key={rule.id}
              onClick={() => setSelectedRule(rule)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                selectedRule.id === rule.id
                  ? 'bg-emerald-600 text-white shadow-sm'
                  : 'bg-muted/70 text-muted-foreground hover:bg-muted hover:text-foreground'
              }`}
            >
              {rule.name}
            </button>
          ))}
        </div>
      </div>

      {/* Simulator & Live Cart Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Interactive Shipping Calculator Simulator */}
        <div className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-border pb-3">
            <span className="text-xs font-mono font-bold text-foreground flex items-center gap-2">
              <MapPin className="w-3.5 h-3.5 text-emerald-600" />
              <span>Target Region: {selectedRule.name}</span>
            </span>
            <span className="text-[11px] font-mono text-muted-foreground">Postcodes: {selectedRule.postcodes}</span>
          </div>

          {/* Cart Slider */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-foreground">Simulated Cart Subtotal:</span>
              <span className="font-mono font-bold text-primary text-sm">${cartTotal} AUD</span>
            </div>
            <input
              type="range"
              min="20"
              max="600"
              step="5"
              value={cartTotal}
              onChange={(e) => setCartTotal(Number(e.target.value))}
              className="w-full h-2 bg-muted rounded-lg appearance-none cursor-pointer accent-primary"
            />
          </div>

          {/* Bulky Hardware Toggle */}
          <div className="p-3.5 rounded-xl bg-muted/40 border border-border flex items-center justify-between">
            <div className="space-y-0.5">
              <div className="text-xs font-bold text-foreground flex items-center gap-1.5">
                <Weight className="w-3.5 h-3.5 text-amber-500" />
                <span>Heavy / Bulky Hardware in Cart (over 20kg or Server Rack)</span>
              </div>
              <p className="text-[11px] text-muted-foreground">Applies commercial freight tailgate surcharge (${selectedRule.bulkySurcharge} AUD).</p>
            </div>
            <input
              type="checkbox"
              checked={isBulky}
              onChange={(e) => setIsBulky(e.target.checked)}
              className="w-4 h-4 rounded text-primary focus:ring-primary"
            />
          </div>

          {/* Live Free Shipping Progress Goal */}
          <div className="p-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5 space-y-2">
            <div className="flex items-center justify-between text-xs">
              <span className="font-bold text-emerald-700 dark:text-emerald-300">
                {remainingForFree === 0 ? '🎉 FREE Delivery Unlocked!' : `Add $${remainingForFree} AUD more for FREE Delivery!`}
              </span>
              <span className="font-mono text-[11px] font-semibold text-emerald-600">{progressPercent}%</span>
            </div>
            <div className="w-full bg-muted h-2 rounded-full overflow-hidden">
              <div className="bg-emerald-500 h-full transition-all duration-300 rounded-full" style={{ width: `${progressPercent}%` }} />
            </div>
          </div>

          {/* Shipping Cost Verdict */}
          <div className="p-4 rounded-xl bg-muted/30 border border-border flex items-center justify-between">
            <span className="text-xs font-semibold text-foreground">Calculated Shipping Rate:</span>
            <span className="text-base font-mono font-bold text-emerald-600 dark:text-emerald-400">
              {remainingForFree === 0 && !isBulky ? (
                'FREE Delivery ($0.00 AUD)'
              ) : isBulky ? (
                `$${selectedRule.flatRate + selectedRule.bulkySurcharge} AUD (Heavy Freight)`
              ) : (
                `$${selectedRule.flatRate} AUD Flat Rate`
              )}
            </span>
          </div>
        </div>

        {/* Right: Generated PHP Hook Code */}
        <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm flex flex-col">
          <div className="px-4 py-3 border-b border-border bg-muted/40 flex items-center justify-between">
            <span className="text-xs font-mono text-muted-foreground">Generated WooCommerce Hook (functions.php)</span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:opacity-90 transition-opacity flex items-center gap-1 shadow-sm"
            >
              <Copy className="w-3 h-3" />
              <span>Copy Code</span>
            </button>
          </div>
          <div className="p-4 flex-1 bg-muted/20 font-mono text-xs text-foreground overflow-x-auto max-h-[380px]">
            <pre className="leading-relaxed text-emerald-700 dark:text-emerald-300">{phpCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
};
